// Mock data for Menu Builder system
export const mockCategories = [
  {
    id: '1',
    name: 'Pizza',
    vatRate: 0.23,
    isDefault: true,
    isOnline: true,
    imageUrl: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Napoje',
    vatRate: 0.23,
    isDefault: false,
    isOnline: true,
    imageUrl: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Dodatki',
    vatRate: 0.23,
    isDefault: false,
    isOnline: true,
    imageUrl: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Pasta',
    vatRate: 0.23,
    isDefault: false,
    isOnline: true,
    imageUrl: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Sałatki',
    vatRate: 0.23,
    isDefault: false,
    isOnline: true,
    imageUrl: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Desery',
    vatRate: 0.23,
    isDefault: false,
    isOnline: true,
    imageUrl: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockSizes = [
  // Pizza sizes
  {
    id: '1',
    categoryId: '1',
    name: 'Mała (20cm)',
    isDefaultInCategory: true,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    categoryId: '1',
    name: 'Średnia (30cm)',
    isDefaultInCategory: false,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    categoryId: '1',
    name: 'Duża (40cm)',
    isDefaultInCategory: false,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Napoje sizes
  {
    id: '4',
    categoryId: '2',
    name: '0.5L',
    isDefaultInCategory: true,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    categoryId: '2',
    name: '1L',
    isDefaultInCategory: false,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pasta sizes
  {
    id: '6',
    categoryId: '4',
    name: 'Standardowa',
    isDefaultInCategory: true,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    categoryId: '4',
    name: 'Duża',
    isDefaultInCategory: false,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sałatki sizes
  {
    id: '8',
    categoryId: '5',
    name: 'Mała',
    isDefaultInCategory: true,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    categoryId: '5',
    name: 'Duża',
    isDefaultInCategory: false,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Desery sizes
  {
    id: '10',
    categoryId: '6',
    name: 'Standardowa',
    isDefaultInCategory: true,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockDishes = [
  // Pizza
  {
    id: '1',
    categoryId: '1',
    name: 'Pizza Margherita',
    description: 'Klasyczna pizza z sosem pomidorowym, mozzarellą i bazylią',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    categoryId: '1',
    name: 'Pizza Pepperoni',
    description: 'Pizza z sosem pomidorowym, mozzarellą i pepperoni',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    categoryId: '1',
    name: 'Pizza Capricciosa',
    description: 'Pizza z szynką, pieczarkami, oliwkami i karczochami',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    categoryId: '1',
    name: 'Pizza Quattro Stagioni',
    description: 'Pizza z szynką, pieczarkami, oliwkami i karczochami',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    categoryId: '1',
    name: 'Pizza Diavola',
    description: 'Ostra pizza z salami, papryczkami chilli i oregano',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    categoryId: '1',
    name: 'Pizza Prosciutto',
    description: 'Pizza z szynką parmeńską, rukolą i parmezanem',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '25',
    categoryId: '1',
    name: 'Pizza Quattro Formaggi',
    description: 'Pizza z czterema rodzajami sera: mozzarella, gorgonzola, parmezan i ricotta',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '26',
    categoryId: '1',
    name: 'Pizza Marinara',
    description: 'Pizza z sosem pomidorowym, czosnkiem, oregano i oliwą z oliwek',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Napoje
  {
    id: '7',
    categoryId: '2',
    name: 'Coca Cola',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    categoryId: '2',
    name: 'Pepsi',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    categoryId: '2',
    name: 'Fanta',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    categoryId: '2',
    name: 'Sprite',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '11',
    categoryId: '2',
    name: 'Woda mineralna',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '12',
    categoryId: '2',
    name: 'Sok pomarańczowy',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pasta
  {
    id: '13',
    categoryId: '4',
    name: 'Spaghetti Carbonara',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '14',
    categoryId: '4',
    name: 'Spaghetti Bolognese',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '15',
    categoryId: '4',
    name: 'Penne Arrabbiata',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '16',
    categoryId: '4',
    name: 'Fettuccine Alfredo',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sałatki
  {
    id: '17',
    categoryId: '5',
    name: 'Sałatka Cezar',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '18',
    categoryId: '5',
    name: 'Sałatka Grecka',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '19',
    categoryId: '5',
    name: 'Sałatka Caprese',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '20',
    categoryId: '5',
    name: 'Sałatka z kurczakiem',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Desery
  {
    id: '21',
    categoryId: '6',
    name: 'Tiramisu',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '22',
    categoryId: '6',
    name: 'Panna Cotta',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '23',
    categoryId: '6',
    name: 'Gelato (3 gałki)',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '24',
    categoryId: '6',
    name: 'Cannoli',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockDishSizes: Array<{
  id: string;
  dishId: string;
  sizeId: string;
  price: number;
  vatSource: 'INHERIT' | 'OVERRIDE';
  vatOverride: number | null;
  isOnline: boolean;
  createdAt: string;
  updatedAt: string;
}> = [
  // Pizza Margherita (1) - wszystkie rozmiary
  {
    id: '1',
    dishId: '1',
    sizeId: '1',
    price: 25.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    dishId: '1',
    sizeId: '2',
    price: 35.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    dishId: '1',
    sizeId: '3',
    price: 45.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pizza Pepperoni (2) - wszystkie rozmiary
  {
    id: '4',
    dishId: '2',
    sizeId: '1',
    price: 28.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    dishId: '2',
    sizeId: '2',
    price: 38.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    dishId: '2',
    sizeId: '3',
    price: 48.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pizza Capricciosa (3) - wszystkie rozmiary
  {
    id: '7',
    dishId: '3',
    sizeId: '1',
    price: 32.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    dishId: '3',
    sizeId: '2',
    price: 42.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    dishId: '3',
    sizeId: '3',
    price: 52.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pizza Quattro Stagioni (4) - wszystkie rozmiary
  {
    id: '10',
    dishId: '4',
    sizeId: '1',
    price: 30.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '11',
    dishId: '4',
    sizeId: '2',
    price: 40.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '12',
    dishId: '4',
    sizeId: '3',
    price: 50.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pizza Diavola (5) - wszystkie rozmiary
  {
    id: '13',
    dishId: '5',
    sizeId: '1',
    price: 29.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '14',
    dishId: '5',
    sizeId: '2',
    price: 39.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '15',
    dishId: '5',
    sizeId: '3',
    price: 49.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pizza Prosciutto (6) - wszystkie rozmiary
  {
    id: '16',
    dishId: '6',
    sizeId: '1',
    price: 31.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '17',
    dishId: '6',
    sizeId: '2',
    price: 41.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '18',
    dishId: '6',
    sizeId: '3',
    price: 51.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Napoje - Coca Cola (7)
  {
    id: '19',
    dishId: '7',
    sizeId: '4',
    price: 8.50,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '20',
    dishId: '7',
    sizeId: '5',
    price: 12.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Napoje - Pepsi (8)
  {
    id: '21',
    dishId: '8',
    sizeId: '4',
    price: 8.50,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '22',
    dishId: '8',
    sizeId: '5',
    price: 12.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Napoje - Fanta (9)
  {
    id: '23',
    dishId: '9',
    sizeId: '4',
    price: 8.50,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '24',
    dishId: '9',
    sizeId: '5',
    price: 12.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Napoje - Sprite (10)
  {
    id: '25',
    dishId: '10',
    sizeId: '4',
    price: 8.50,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '26',
    dishId: '10',
    sizeId: '5',
    price: 12.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Napoje - Woda mineralna (11)
  {
    id: '27',
    dishId: '11',
    sizeId: '4',
    price: 5.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '28',
    dishId: '11',
    sizeId: '5',
    price: 7.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Napoje - Sok pomarańczowy (12)
  {
    id: '29',
    dishId: '12',
    sizeId: '4',
    price: 9.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '30',
    dishId: '12',
    sizeId: '5',
    price: 13.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pasta - Spaghetti Carbonara (13)
  {
    id: '31',
    dishId: '13',
    sizeId: '6',
    price: 28.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '32',
    dishId: '13',
    sizeId: '7',
    price: 35.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pasta - Spaghetti Bolognese (14)
  {
    id: '33',
    dishId: '14',
    sizeId: '6',
    price: 26.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '34',
    dishId: '14',
    sizeId: '7',
    price: 33.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pasta - Penne Arrabbiata (15)
  {
    id: '35',
    dishId: '15',
    sizeId: '6',
    price: 24.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '36',
    dishId: '15',
    sizeId: '7',
    price: 31.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pasta - Fettuccine Alfredo (16)
  {
    id: '37',
    dishId: '16',
    sizeId: '6',
    price: 30.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '38',
    dishId: '16',
    sizeId: '7',
    price: 37.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sałatki - Sałatka Cezar (17)
  {
    id: '39',
    dishId: '17',
    sizeId: '8',
    price: 22.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '40',
    dishId: '17',
    sizeId: '9',
    price: 28.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sałatki - Sałatka Grecka (18)
  {
    id: '41',
    dishId: '18',
    sizeId: '8',
    price: 20.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '42',
    dishId: '18',
    sizeId: '9',
    price: 26.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sałatki - Sałatka Caprese (19)
  {
    id: '43',
    dishId: '19',
    sizeId: '8',
    price: 18.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '44',
    dishId: '19',
    sizeId: '9',
    price: 24.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sałatki - Sałatka z kurczakiem (20)
  {
    id: '45',
    dishId: '20',
    sizeId: '8',
    price: 24.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '46',
    dishId: '20',
    sizeId: '9',
    price: 30.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Desery - Tiramisu (21)
  {
    id: '47',
    dishId: '21',
    sizeId: '10',
    price: 15.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Desery - Panna Cotta (22)
  {
    id: '48',
    dishId: '22',
    sizeId: '10',
    price: 12.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Desery - Gelato (23)
  {
    id: '49',
    dishId: '23',
    sizeId: '10',
    price: 10.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Desery - Cannoli (24)
  {
    id: '50',
    dishId: '24',
    sizeId: '10',
    price: 8.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pizza Quattro Formaggi (25) - wszystkie rozmiary
  {
    id: '51',
    dishId: '25',
    sizeId: '1',
    price: 33.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '52',
    dishId: '25',
    sizeId: '2',
    price: 43.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '53',
    dishId: '25',
    sizeId: '3',
    price: 53.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Pizza Marinara (26) - wszystkie rozmiary
  {
    id: '54',
    dishId: '26',
    sizeId: '1',
    price: 22.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '55',
    dishId: '26',
    sizeId: '2',
    price: 32.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '56',
    dishId: '26',
    sizeId: '3',
    price: 42.00,
    vatSource: 'INHERIT',
    vatOverride: null,
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockAddonGroups = [
  {
    id: '1',
    name: 'Dodatki do pizzy',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Sosy',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Dodatki do sałatek',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Dodatki do makaronów',
    isOnline: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockAddonItems = [
  // Dodatki do pizzy
  {
    id: '1',
    groupId: '1',
    name: 'Extra ser',
    price: 3.00,
    isOnline: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    groupId: '1',
    name: 'Extra szynka',
    price: 4.00,
    isOnline: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    groupId: '1',
    name: 'Extra pieczarki',
    price: 2.50,
    isOnline: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    groupId: '1',
    name: 'Extra oliwki',
    price: 3.50,
    isOnline: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    groupId: '1',
    name: 'Extra pepperoni',
    price: 4.50,
    isOnline: true,
    sortOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '18',
    groupId: '1',
    name: 'Extra ananas',
    price: 3.00,
    isOnline: true,
    sortOrder: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '19',
    groupId: '1',
    name: 'Extra cebula',
    price: 2.00,
    isOnline: true,
    sortOrder: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '20',
    groupId: '1',
    name: 'Extra papryka',
    price: 2.50,
    isOnline: true,
    sortOrder: 8,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '21',
    groupId: '1',
    name: 'Extra rukola',
    price: 3.50,
    isOnline: true,
    sortOrder: 9,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '22',
    groupId: '1',
    name: 'Extra pomidory',
    price: 2.50,
    isOnline: true,
    sortOrder: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sosy
  {
    id: '6',
    groupId: '2',
    name: 'Sos pomidorowy',
    price: 2.00,
    isOnline: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    groupId: '2',
    name: 'Sos czosnkowy',
    price: 2.50,
    isOnline: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    groupId: '2',
    name: 'Sos BBQ',
    price: 2.50,
    isOnline: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    groupId: '2',
    name: 'Sos ranch',
    price: 2.50,
    isOnline: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '23',
    groupId: '2',
    name: 'Sos pomidorowy z bazylią',
    price: 2.50,
    isOnline: true,
    sortOrder: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '24',
    groupId: '2',
    name: 'Sos pikantny',
    price: 2.50,
    isOnline: true,
    sortOrder: 6,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '25',
    groupId: '2',
    name: 'Sos czosnkowy z ziołami',
    price: 3.00,
    isOnline: true,
    sortOrder: 7,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Dodatki do sałatek
  {
    id: '10',
    groupId: '3',
    name: 'Extra kurczak',
    price: 6.00,
    isOnline: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '11',
    groupId: '3',
    name: 'Extra ser feta',
    price: 4.00,
    isOnline: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '12',
    groupId: '3',
    name: 'Extra awokado',
    price: 5.00,
    isOnline: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '13',
    groupId: '3',
    name: 'Extra orzechy',
    price: 3.00,
    isOnline: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Dodatki do makaronów
  {
    id: '14',
    groupId: '4',
    name: 'Extra kurczak',
    price: 8.00,
    isOnline: true,
    sortOrder: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '15',
    groupId: '4',
    name: 'Extra boczek',
    price: 6.00,
    isOnline: true,
    sortOrder: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '16',
    groupId: '4',
    name: 'Extra pieczarki',
    price: 4.00,
    isOnline: true,
    sortOrder: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '17',
    groupId: '4',
    name: 'Extra parmezan',
    price: 3.00,
    isOnline: true,
    sortOrder: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockModifiers = [
  {
    id: '1',
    groupId: '1',
    selectionType: 'MULTI' as const,
    minSelect: 0,
    maxSelect: 5,
    includedFreeQty: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    groupId: '2',
    selectionType: 'SINGLE' as const,
    minSelect: 0,
    maxSelect: 1,
    includedFreeQty: 1,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    groupId: '3',
    selectionType: 'MULTI' as const,
    minSelect: 0,
    maxSelect: 3,
    includedFreeQty: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    groupId: '4',
    selectionType: 'MULTI' as const,
    minSelect: 0,
    maxSelect: 4,
    includedFreeQty: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockGroupAssignments = [
  // Dodatki do pizzy - przypisane do kategorii Pizza
  {
    id: '1',
    groupId: '1',
    categoryId: '1',
    dishId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Sosy - przypisane do kategorii Pizza
  {
    id: '2',
    groupId: '2',
    categoryId: '1',
    dishId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Dodatki do sałatek - przypisane do kategorii Sałatki
  {
    id: '3',
    groupId: '3',
    categoryId: '5',
    dishId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  // Dodatki do makaronów - przypisane do kategorii Pasta
  {
    id: '4',
    groupId: '4',
    categoryId: '4',
    dishId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];



